@startuml
left to right direction
class 利用者テーブル{
I D
メールアドレス
利用者名
ソルト
パスワード
削除キー
}

class 認証コード保管テーブル{
I D
メールアドレス
認証コード
有効期限
}

class タスクテーブル{
I D
タスク名
タスク分類ID（FK）
利用者ID（FK）
チームID（FK）
進行度
ファイルパス
登録日
完了日
削除キー
}

class タスク分類テーブル{
I D
タスク分類名
利用者ID（FK）
チームID（FK）
削除キー
}

class 進行度テーブル{
I D
タスクID（FK）
進行度
}

class チームテーブル{
I D
チーム名
チーム管理者ID（FK）
無効設定
削除キー    
}

class チームメンバーテーブル{
利用者ID
チームID
削除キー
}

class チャットテーブル{
I D
コメント
利用者ID（FK）
チームID（FK）
投稿日
削除キー
}

class タスクゲームテーブル{
I D
タイトル
ゴール
内容
基本情報
}

class ゲーム問題テーブル{
I D
タスクゲームID（FK）
選択肢
日数
削除キー
}

class スコア管理テーブル{
I D
タスクゲームID（FK）
利用者ID（FK）
スコア1
スコア2
総合評価
削除キー
}

利用者テーブル "1"--"1" 認証コード保管テーブル
利用者テーブル "1"--* タスクテーブル
利用者テーブル "1"--* チームメンバーテーブル
チームメンバーテーブル *--"1" チームテーブル
利用者テーブル "1"--* チャットテーブル
利用者テーブル "1"--* タスク分類テーブル
タスクテーブル "1"--* 進行度テーブル
タスクテーブル *--"1" タスク分類テーブル
チームテーブル "1"--* タスクテーブル
チームテーブル "1"--* チャットテーブル
チームテーブル "1"--* タスク分類テーブル

利用者テーブル "1"--* スコア管理テーブル

タスクゲームテーブル "1"--* ゲーム問題テーブル
タスクゲームテーブル "1"--"1" スコア管理テーブル

hide circle
@enduml