@startuml
left to right direction
[*] --> 待機中
待機中 --> 印刷中 : 待機完了/印刷を開始する
印刷中 --> 用紙無し : 用紙がなくなる[補充できない]/処理を終了する
用紙無し --> [*]
@enduml
' （１）あるプリンターには「待機中」「印刷中」「用紙無し」の各状態があります。これらの状態の
' 遷移をステートマシン図で描いてください。