@startuml
left to right direction
[*] --> 待機中
state c <<choice>>
state c <<choice>>
待機中 --> c
c --> 印刷中 : 待機完了
c --> 用紙無し : 用紙が不足
印刷中 --> [*] : 印刷完了
用紙無し --> [*] : 印刷失敗
@enduml
' （１）あるプリンターには「待機中」「印刷中」「用紙無し」の各状態があります。これらの状態の
' 遷移をステートマシン図で描いてください。