@startuml
left to right direction
[*] --> メニュー : 接続
メニュー --> 今の順番
メニュー --> 予約と確認
state c <<choice>>
state c <<choice>>
state c <<choice>>
予約と確認 --> c
c --> メニュー : 取消
c --> あなたの順番 :登録、確認

今の順番 --> [*]
あなたの順番 --> [*]
@enduml