@startuml
left to right direction
actor 利用者
actor 看護師
rectangle 予約システム{
usecase 予約をするas a
usecase 予約を確認する as b
usecase 予約を取り消す as c
usecase 今の順番を確認する as d
}
利用者 --> a
利用者 --> b
利用者 --> c
利用者 --> d
d <-- 看護師
@enduml