@startuml
state 部屋{
state entry <<entryPoint>>
state exit <<exitPoint>>
entry -right-> 空室状態
空室状態 --> 予約済状態
予約済状態 --> 空室状態
空室状態 --> 使用状態
使用状態 --> 空室状態
空室状態 --> exit
}
[*] --> entry
exit -> [*]
@enduml
' 部屋オブジェクトには、空室状態と、予約済状態、使用状態がある。各状態のイベントや状態の入れ子を
' について考察し、部屋オブジェクトのステートマシン図を作成しなさい。