@startuml
hide footbox
participant "user:利用者" as user
participant ":予約画面" as reserve

activate user
user ->> reserve : ログイン()
activate reserve
reserve -> reserve : 認証()
activate reserve
' deactivate reserve
' user <-- reserve 
deactivate reserve
deactivate user
@enduml