@startuml
left to right direction
object "<u>顧客情報１:顧客</u>" as A{
名前=Aさん
チェックイン日=5月3日
滞在期間=2泊
}
object "<u>顧客情報２:顧客</u>" as B{
名前=Bさん
チェックイン日=5月3日
滞在期間=2泊
}
object "<u>301号室:部屋</u>" as r1{
タイプ=シングル
価格=11,000円
キャンペーン価格=9,000円
}
object "<u>302号室:部屋</u>" as r2{
タイプ=シングル
価格=11,000円
キャンペーン価格=9,000円
}
object "<u>303号室:部屋</u>" as r3{
タイプ=シングル
価格=11,000円
キャンペーン価格=9,000円
}
object "<u>ホテルUML:ホテル</u>" as h{
301号室
302号室
303号室
}
A -up- r1
B -up- r3
h -- r1
h -- r2
h -- r3
@enduml