@startuml
left to right direction
actor 利用者
actor 看護師
rectangle 予約{
usecase メニューを閲覧する
usecase 予約と確認を閲覧する
usecase 予約をする
usecase 予約を確認する
usecase 予約を取り消す
usecase 情報を入力する
usecase 今の順番を確認する
usecase あなたの順番を確認する
usecase 患者番号を更新する
}
利用者 --> メニューを閲覧する
予約と確認を閲覧する ..> 情報を入力する : << include >>
メニューを閲覧する --> 予約と確認を閲覧する

予約と確認を閲覧する --> 予約をする
予約と確認を閲覧する --> 予約を確認する
予約と確認を閲覧する -left-> 予約を取り消す
予約をする --> あなたの順番を確認する
予約を確認する --> あなたの順番を確認する
メニューを閲覧する <-- 予約を取り消す
メニューを閲覧する --> 今の順番を確認する
看護師 --> 患者番号を更新する
患者番号を更新する ..> 今の順番を確認する : <<extend>>
@enduml